theme: jekyll-theme-minimal
title: Ghazaleh's homepage
description: Hi and welcome to my humble abode! I'm Ghazaleh, a full stack developer with a passion for design. You can follow my personal projects here.
